name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ASP_NET_Core_MVC_Tutorial_App/ASP_NET_Core_MVC_Tutorial_App.csproj

    - name: Build
      run: dotnet build ASP_NET_Core_MVC_Tutorial_App/ASP_NET_Core_MVC_Tutorial_App.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ASP_NET_Core_MVC_Tutorial_App/ASP_NET_Core_MVC_Tutorial_App.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: chasefranklinaspcoremvctutorial
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish